version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:8000"
    environment:
      - SECRET_KEY=dev-secret-key-change-in-production
      - FLASK_ENV=development
    volumes:
      - ./app.py:/app/app.py
      - ./templates:/app/templates
    restart: unless-stopped
